[gcp_service_account]
type = "service_account"
project_id = "renodat"
private_key_id = "a9e531a0f1607bdd53a3276d612371bbf013d7ea"
private_key = '''-----BEGIN PRIVATE KEY-----
MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQDNoOAa6m4mTCjq
ueBD0s95UquG2EIyx/tMx7YYX2alAeIVBL9VLPCX7LMW+FdHzHJ6dxac+6IbRxcp
Z8XX2s/iOee5h08YyRM6E1+dVydiL2Is15rfHYKzt8Th6XquHZcz3XNOnSEiWd9F
E3aJ1hSoyo/E1I4vNAWkHSxAbDY6EG6rIXVdxP5Dl2y5jei5sJt/eHHqRir16OnA
e9RD6zNctq1heZ/sAkuUAqRlype0YFm4vzn1UGiySA7bpOUh//vwCDDnWRNNtEKv
2NsMF5HTLSmxi0WmsZ715dUnVLJ7OqUWIKdFVhvvuB0lKctyqP6FAwno5dBYLEEN
ajMYPlOLAgMBAAECggEANG5FRkepP2Wi9zre5pxNn6NHLjJdKsKYHps7oJpOu1sw
EOjtemPjkvFdNsmqw5lrRTOxVeTJkEf/rWSS6zeVUxstrT5Fmk3G88N12VIcLipj
z4hIKoTFS1rbvjjAub28zJI2MQDarn4Y8m2Eh5/JE8LWhrsl5/5NQ+vWWTTeXM5X
gn2/mopkN/nJJvHnxBQGzFOj5T0KsZRaubsGZqbtGB4YV0wOf574nPMhlTwWx67A
qI4XT8e2+G8jix1XqiTvbyVOWPx6I9IwUH6ZCmfFYKUS0DgogqWSxyVKKkvW7idx
gzkzDhjNUGuWqOH2CKw6Cd9xfSVX0UoREmSQMVaw8QKBgQD2m39I7cFTBUKGHJji
zyqqQtJ8Ls6cgYkX0gupm3AZTUtYI6/Y6qbL0Bl7mdiuicAIR6oeCWHf7jLm4fVj
FDKWlMqG4K8uvCqlWB68ag9vmZXMDBPiT4a7Q65BlQndqdxPQF6nHX00/vS1fS0Y
eKbew+rSFZIT9sThCKs0LGCQcQKBgQDVddHU7UyKci5eq45RCVt4Z6q+cAqYmCkQ
DyZJCsRhPhpqNze1AnQHrtWz7LYQa0pM5wJ/ZvDjv1bqlds/yelYdLqsT9VQi38e
WN6kLL85DXikjJR2GjtrqbLD34jB/XH68sE5Ap1qw19buvGCZU+rTsGYSta2V611
C6NL45phuwKBgQCIjBEukHc7QO5U1ADTlWJKZDWoDULZ5d/DEMrkXuzzFZlidGAp
+8PflpqFleokuqFZ9FR9zTQkigAlV3hIJCbeugRqKn7Vodr7Mo/SQ+fII4KOOSHJ
bb9scU1Lgvqzgho6x6mhXvK1JXbaBzWxFx1Ou6yKJud7pmfdMq+Zc/kEAQKBgQCJ
cwxiZ0rZ+xwQqbdCRxw3M8mmRs8L4y7NwHOOpPg/BZZMvrGIRMQiDlpdORcjC3MU
gcwB7W8/t31oIIbFVGaFJuTs/5sD+k8oY2E5pfab7ii5DCysv8dzVBpgNhgBkglK
5fW1mBF1JcjJcF8C7+mVDWlrfwUy9NIkhBHqU+yc8QKBgQCjpAH8oT7/4mZuanjX
YO8t+7vQX9sIZ64Nq4bOVgEWSGQChM9M/MQPDl1VJPcMEYGwrYWPLisypI79MClv
0/UhYBPq80LjdYLuWYxExcTOv202+/yb1ILHJwrvMeAHC98VLXygbcEY7ulCCvKn
dCKhfFrGH1c+iD8q5bxYfpH9nA==
-----END PRIVATE KEY-----
'''
client_email = "hibadoi@renodat.iam.gserviceaccount.com"
client_id = "104011136980325886539"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/hibadoi%40renodat.iam.gserviceaccount.com"
